### ISSUE TITLE
Unable to 'chat`

### ISSUE THREAD

**Issue by vudotech** [treyworks/treyworks-chat-plugin#1] opened 2024-01-11 06:06 UTC
After downloading the zip from this Github reop and installing the WP plugin and updated my API key as well as Assistant ID. When I started chatting I got stuck with an eternal loading animation in the chatbox:

<img width="288" alt="Screenshot 2024-01-11 at 13 04 03" src="https://github.com/treyworks/treyworks-chat-plugin/assets/126435939/7829a0dc-d7ec-4240-b461-db5d4dd3cf31">

Here is the output that I am getting in my browser console:

```
Warning: Invalid DOM property `class`. Did you mean `className`?
svg
test_plugin/wp-content/plugins/treyworks-chat-plugin-main/component/dist/tw-chat-ui.js?ver=1.0.0:23338:12
button
div
test_plugin/wp-content/plugins/treyworks-chat-plugin-main/component/dist/tw-chat-ui.js?ver=1.0.0:23343:21 tw-chat-ui.js:2691:62
downloadable font: font-display timeout, webfont not used (font-family: "Inter" style:normal weight:200..900 stretch:100 src index:0) source: https://tylermonette.com/test_plugin/wp-content/themes/extendable/assets/fonts/inter/InterVariable.woff2
Error fetching messages: 
Object { stack: "test_plugin/wp-content/plugins/treyworks-chat-plugin-main/component/dist/tw-chat-ui.js?ver=1.0.0:21937:110\nI_@/test_plugin/wp-content/plugins/treyworks-chat-plugin-main/component/dist/tw-chat-ui.js?ver=1.0.0:22498:45\nSe@/test_plugin/wp-content/plugins/treyworks-chat-plugin-main/component/dist/tw-chat-ui.js?ver=1.0.0:22649:9\n", message: "Request failed with status code 404", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…} }
tw-chat-ui.js:23299:30
```

**Comment by treyworks** [comment] 2024-01-11 12:20
Thank you for your effort in testing the plugin and for your valuable feedback. It appears that some updates weren't pushed as expected yesterday, which might have led to the occurrence of the ERR_BAD_REQUEST error. Please pull the most recent commit and run the test once more. Your further feedback would be greatly appreciated.

**Comment by vudotech** [comment] 2024-01-12 06:39
After doing the latest pull I am still getting the same errors in my browser. Seems like my assistant is not replying back. 

As a reference I am using WordPress on with PHP version 8.1.

Here is the output:

```
tw-chat-ui.js:23304:84
Error fetching messages: 
Object { stack: "It/test/wp-content/plugins/treyworks-chat-plugin-main/component/dist/tw-chat-ui.js?ver=1.0.0:21937:110\nI_@/test/wp-content/plugins/treyworks-chat-plugin-main/component/dist/tw-chat-ui.js?ver=1.0.0:22498:45\nye@/test/wp-content/plugins/treyworks-chat-plugin-main/component/dist/tw-chat-ui.js?ver=1.0.0:22649:9\n", message: "Request failed with status code 404", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…} }
tw-chat-ui.js:23307:15
​
code: "ERR_BAD_REQUEST"
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​
message: "Request failed with status code 404"
​
name: "AxiosError"
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
response: Object { data: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL was not found on this server.</p>\n<p>Additionally, a 404 Not Found\nerror was encountered while trying to use an ErrorDocument to handle the request.</p>\n</body></html>\n', status: 404, statusText: "Not Found", … }
```

**Comment by treyworks** [comment] 2024-01-13 14:57
Thanks for the browser console output!  The issue was that the component wasn't using the site URL for endpoint calls, causing 404s in non-root WordPress setups.

I've pushed a fix today that addresses this.  Please update to the latest code and confirm the issue is resolved. If you continue to see 404s, please provide more details about your WordPress setup and any relevant error messages.

**Closed** 2024-02-25 15:08 UTC
